/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Limits */
        get: operations["limits_api_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check */
        post: operations["check_api_preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        /** Start */
        post: operations["start_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_runs__run_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate
         * @description New take of a shot artifact: shifts the key and seed, so it is really new; the rest
         *     comes from the cache. Approval is bound to the frame hash: same frames are not asked.
         */
        post: operations["regenerate_api_runs__run_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/rewrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rewrite
         * @description New script take (same lines, new staging and video prompts) and the run again: the
         *     way out when a model refused a prompt. Stops for approval only if the run was started
         *     with review: a run without stops stays without stops.
         */
        post: operations["rewrite_api_runs__run_id__rewrite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume
         * @description Resume from where it stopped (error, a fal job still running). Nothing paid is
         *     repeated: artifacts come from the cache, unfinished fal jobs are picked up from disk.
         */
        post: operations["resume_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /** Decisions */
            decisions: {
                [key: string]: "approve" | "regenerate";
            };
        };
        /** Artifacts */
        Artifacts: {
            /** Script */
            script: {
                [key: string]: unknown;
            } | null;
            /** Casting */
            casting: {
                [key: string]: unknown;
            } | null;
            /** Voices */
            voices: components["schemas"]["VoiceArtifact"][];
            /** Keyframes */
            keyframes: components["schemas"]["FrameArtifact"][];
            /** Clips */
            clips: components["schemas"]["ClipArtifact"][];
            /** Final */
            final: string | null;
        };
        /** AsrCheck */
        AsrCheck: {
            /** Expected */
            expected: string;
            /** Heard */
            heard: string;
            /** Expected Norm */
            expected_norm: string;
            /** Heard Norm */
            heard_norm: string;
            /** Wer */
            wer: number;
            /** Passed */
            passed: boolean;
            /** Attempt */
            attempt: number;
            /** Model */
            model: string;
            /**
             * Diff
             * @default []
             */
            diff: components["schemas"]["WordDiff"][];
        };
        /** ClipArtifact */
        ClipArtifact: {
            /** Shot Id */
            shot_id: string;
            /** Url */
            url: string | null;
            /**
             * Stage
             * @default video
             * @enum {string}
             */
            stage: "video" | "lipsync";
        };
        /**
         * FrameArtifact
         * @description Cut frame: shot shot_id starts from the frame of source_shot at at_s (spec keyframe.md).
         */
        FrameArtifact: {
            /** Shot Id */
            shot_id: string;
            /** Url */
            url: string | null;
            /** Approved */
            approved: boolean;
            /** Source Shot */
            source_shot?: string | null;
            /** At S */
            at_s?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InterruptFrame
         * @description Cut frame to approve: shot shot_id starts from the frame of source_shot at at_s.
         */
        InterruptFrame: {
            /** Shot Id */
            shot_id: string;
            /** Path */
            path: string;
            /** Prompt */
            prompt: string;
            /** Source Shot */
            source_shot?: string | null;
            /** At S */
            at_s?: number | null;
        };
        /** InterruptView */
        InterruptView: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "approve_script" | "approve_cut_frames";
            /**
             * Frames
             * @default []
             */
            frames: components["schemas"]["InterruptFrame"][];
            /** Script */
            script?: {
                [key: string]: unknown;
            } | null;
            plan?: components["schemas"]["VideoPlan"] | null;
            /** Next Cost Usd */
            next_cost_usd?: number | null;
            /** Error */
            error?: string | null;
        };
        /** Limits */
        Limits: {
            /** Min Words Per Line */
            min_words_per_line: number;
            /** Max Words Per Line */
            max_words_per_line: number;
            /** Max Words Total */
            max_words_total: number;
            /** Max Lines */
            max_lines: number;
            /** Forbidden Chars */
            forbidden_chars: string;
            /** Max Run Cost Usd */
            max_run_cost_usd: number;
            /** Max Daily Cost Usd */
            max_daily_cost_usd: number;
            /** Deliveries */
            deliveries: string[];
            /** Models By Mode */
            models_by_mode: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Notes By Mode */
            notes_by_mode: {
                [key: string]: string[];
            };
        };
        /** NodeView */
        NodeView: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "error" | "waiting";
            /**
             * Duration S
             * @default 0
             */
            duration_s: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Runs
             * @default 0
             */
            runs: number;
            /** Error */
            error?: string | null;
        };
        /** RegenerateRequest */
        RegenerateRequest: {
            /**
             * Node
             * @enum {string}
             */
            node: "voice" | "video" | "lipsync";
            /** Shot Id */
            shot_id: string;
        };
        /**
         * Rejected
         * @description A model's content checker refused a shot: resuming repeats the same request, so the UI
         *     offers a new take of that shot or a rewritten script instead.
         */
        Rejected: {
            /** Node */
            node: string;
            /** Shot Id */
            shot_id: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Idea */
            idea: string;
            /** Status */
            status: string;
            /** Cost Usd */
            cost_usd: number;
            /** Updated */
            updated: number;
        };
        /** RunView */
        RunView: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Mode */
            mode: string | null;
            /** Brief */
            brief: {
                [key: string]: unknown;
            } | null;
            /** Nodes */
            nodes: components["schemas"]["NodeView"][];
            /** Cost Usd */
            cost_usd: number;
            /** Max Run Cost Usd */
            max_run_cost_usd: number;
            artifacts: components["schemas"]["Artifacts"];
            asr: components["schemas"]["AsrCheck"] | null;
            /** Voice Checks */
            voice_checks: components["schemas"]["VoiceCheck"][];
            sync: components["schemas"]["SyncCheck"] | null;
            /** Models */
            models: {
                [key: string]: string;
            };
            interrupt: components["schemas"]["InterruptView"] | null;
            /** Error */
            error: string | null;
            rejected?: components["schemas"]["Rejected"] | null;
            /** Auto Approve */
            auto_approve?: boolean | null;
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ShotPlan
         * @description Exactly what goes to the video model for a shot (spec approve_script.md).
         */
        ShotPlan: {
            /** Shot Id */
            shot_id: string;
            /** Character Id */
            character_id: string;
            /** Line */
            line: string;
            /** Delivery */
            delivery: string;
            /**
             * Start
             * @enum {string}
             */
            start: "text" | "cut_frame";
            /** Source Shot */
            source_shot?: string | null;
            /** Shot S */
            shot_s: number;
            /** Clip S */
            clip_s: number;
            /** Prompt */
            prompt: string;
        };
        /** ShotSync */
        ShotSync: {
            /** Shot Id */
            shot_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "ok" | "off" | "n/a";
            /** Face Ratio */
            face_ratio: number;
            /** Best Lag Ms */
            best_lag_ms?: number | null;
            /** Corr */
            corr?: number | null;
            /** Mouth Speech Ratio */
            mouth_speech_ratio?: number | null;
            /**
             * Mouth
             * @default []
             */
            mouth: (number | null)[];
            /**
             * Env
             * @default []
             */
            env: number[];
        };
        /**
         * StartRequest
         * @description Same line rules as the CLI (Brief): FastAPI returns 422 with the field.
         */
        StartRequest: {
            /** Idea */
            idea: string;
            /** Lines */
            lines: string[];
            /**
             * Mode
             * @default fake
             * @enum {string}
             */
            mode: "fake" | "real";
            /**
             * Auto Approve
             * @default false
             */
            auto_approve: boolean;
            /**
             * Fresh
             * @default false
             */
            fresh: boolean;
        };
        /** SyncCheck */
        SyncCheck: {
            /** Passed */
            passed: boolean;
            /**
             * Gate
             * @enum {string}
             */
            gate: "warn" | "block";
            /** Shots */
            shots: components["schemas"]["ShotSync"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoPlan */
        VideoPlan: {
            /** Model */
            model: string;
            /** Negative Prompt */
            negative_prompt?: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Shots */
            shots: components["schemas"]["ShotPlan"][];
        };
        /** VoiceArtifact */
        VoiceArtifact: {
            /** Shot Id */
            shot_id: string;
            /** Url */
            url: string | null;
            /** Tts Text */
            tts_text?: string | null;
            /** Line */
            line?: string | null;
            /** Voice Id */
            voice_id?: string | null;
            /** Seed */
            seed?: number | null;
        };
        /** VoiceCheck */
        VoiceCheck: {
            /** Shot Id */
            shot_id: string;
            /** Passed */
            passed: boolean;
            /** Wer */
            wer: number;
            /** Heard */
            heard: string;
            /**
             * Diff
             * @default []
             */
            diff: components["schemas"]["WordDiff"][];
            /** Attempt */
            attempt: number;
        };
        /** WordDiff */
        WordDiff: {
            /**
             * Op
             * @enum {string}
             */
            op: "replace" | "delete" | "insert";
            /** Expected */
            expected: string;
            /** Heard */
            heard: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    limits_api_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Limits"];
                };
            };
        };
    };
    check_api_preflight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    start_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_runs__run_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_runs__run_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rewrite_api_runs__run_id__rewrite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
